### PR TITLE
Add Glitch codebase

### PR DESCRIPTION
**Pull request by bboy114crew**
Glitch 
Code, collaborate, & ship in seconds
Create your next web project in your browser with no setup and we'll instantly deploy it.

### CODE REVIEW

**Comment by ladifire** [comment]
@bboy114crew where you get this source code? is it opensource?

**Comment by bboy114crew** [comment]
> @bboy114crew where you get this source code? is it opensource?

Not yet for now. I get it from soure-map :D
In our codebase, we have two OSSs are react.js and gastby site.

**Comment by ladifire** [comment]
@bboy114crew reactjs.org was removed, but I've kept gatsby homepage codebase since it's not an opensource project.

hmm, sorry it's look like you're submitting an opensource project. Isn't it?

**Comment by bboy114crew** [comment]
> @bboy114crew reactjs.org was removed, but I've kept Gatsby's homepage codebase since it's not an open-source project.
> 
> hmm, sorry it looks like you're submitting an open-source project. Isn't it?

My bad, Gatsby site is not open source yet and Glitch also 😄

**Comment by ladifire** [comment]
@bboy114crew yes, I've re-check and Glitch is not an opensource, I'll merge it now.
Thank you very much!

**Pull request merged**
